INSERT INTO Katoon VALUES
(1,'my body has been possessed by someone','Ongoing','Fantasy','lorem ipsum dolor sit amet, consectetur adipiscing elit','Monday'),
(2,'my clueless love diary','Completed','Romance','lorem ipsum dolor sit amet','Tuesday'),
(3,'My Secretly Hot Husband','Ongoing','Romance','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua','Wednesday'),
(4,'night owls summer skies','Completed','Slice of Life','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','Thursday'),
(5,'omniscient reader','Ongoing','Fantasy','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam','Friday'),
(6,'one husband is enough','Completed','Romance','lorem ipsum dolor sit amet, consectetur adipiscing elit','Saturday'),
(7,'our secret alliance','Ongoing','Romance','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt','Sunday'),
(8,'A Beast Tamed By The Villainess','Completed','Drama','lorem ipsum dolor sit amet','Monday'),
(10,'sweet home','Completed','Horror','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore','Wednesday'),
(11,'The First Night With The Duke','Ongoing','Romance','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua','Friday'),
(12,'The Greatest Estate Developer','Completed','Comedy','lorem ipsum dolor sit amet','Tuesday'),
(13,'the little revenge plan of a villainess','Ongoing','Fantasy','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation','Thursday'),
(14,'the mad bloodhound’s dying master','Completed','Action','lorem ipsum dolor sit amet, consectetur adipiscing elit','Saturday'),
(15,'the time limited villainess wishes for the f...','Ongoing','Fantasy','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat','Sunday'),
(16,'to you who killed me','Completed','Drama','lorem ipsum dolor sit amet','Monday'),
(17,'welcome to the rose mansion','Ongoing','Horror','lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua','Thursday'),
(18,'your letter','Completed','Romance','lorem ipsum dolor sit amet, consectetur adipiscing elit','Tuesday');
